In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
#NumPy array

arr = np.array([1, 2])
print(arr)

a = np.array([1, "A" ,True])
print(a.dtype)

b = np.array([1, 2, 3])
print(b.dtype)

c = np.array([1.1, 2.3])
print(c.dtype)

[1 2]
<U11
int32
float64


In [3]:
#ndarray and list objects - size comparison

from sys import getsizeof

lst = [1 ,2, 3, 4, 5, 6, 7, 8, 9, 10]
print(getsizeof(lst))

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(getsizeof(arr))

136
144


In [4]:
#operation & np.sqrt

lst = [1, 2, 3]
arr = np.array(lst)
arr = np.sqrt(arr)
print(arr)

[1.         1.41421356 1.73205081]


In [5]:
#exercise

test_1 = np.array([92, 94, 88, 91 ,87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)


jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = [test_1[1], test_1[2]]
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print(student_scores[2][0])

print(student_scores[:, 3])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94, 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[91 93 90]


In [6]:
#logical operations w/ arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = arr > 5
print(mask)


selected = arr[(arr > 5) & (arr < 8)]
print(selected)

[False False False False False  True  True  True  True  True]
[6 7]
